package hu.unideb.inf.rft.neuban.web.mail.message;


public enum MailMessageCategory {

	CATEGORY_REGISTRATION,
	CATEGORY_ADD_USER_TO_BOARD,
	CATEGORY_ADD_USER_TO_BOARD_CIRCULAR,
	CATEGORY_REMOVE_USER_FROM_BOARD,
	CATEGORY_REMOVE_USER_FROM_BOARD_CIRCULAR,
	CATEGORY_ADD_USER_TO_CARD,
	CATEGORY_REMOVE_USER_FROM_CARD,
	CATEGORY_CARD_MOVING
}
